[tool.basedpyright]
extends = "bazel-bin/ide_support.runfiles/score_python_basics~/pyproject.toml"
verboseOutput = true

exclude = [
    "**/__pycache__",
    "**/.*",
    "**/bazel-*",

]

[tool.ruff.format]
quote-style = "preserve"

[tool.ruff]
exclude = [
   "nlohmann_json/docs/mkdocs/scripts",
   "nlohmann_json/tests",
   "nlohmann_json/tools",
]
